# Generated by Django 5.2.1 on 2025-05-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'Короткая ссылка на рецепт', 'verbose_name_plural': 'Короткие ссылки на рецепт'},
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Уникальный код'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
